db:
  db_user: "postgres"
  db_pass: "postgres"
  db_name: "postgres"
  ssl_mode: "disable"
  port: "5432"
server:
  timeout: 15s
  idle_timeout: 30s
  address: "0.0.0.0:63342"
broker:
  max_reconnects: 5
  reconnect_wait: 5s
  address: "nats://nats:4222"
  retry: Yes
file_server:
  storage_folder: "./data" # absolute path folder or from
  url_path: "static" # address/<url_path>/
receiver_addr: "ws://0.0.0.0:63345/"